[[main]]
  name = "Posts"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "Timeline"
  pageRef = "timeline"
  weight = 15

[[main]]
  name = "Topics"
  weight = 20

[[main]]
  name = "Web & API"
  parent = "Topics"
  pageRef = "tags/web"
  weight = 21

[[main]]
  name = "Active Directory"
  parent = "Topics"
  pageRef = "tags/active-directory"
  weight = 22

[[main]]
  name = "Mobile"
  parent = "Topics"
  pageRef = "tags/mobile"
  weight = 23

[[main]]
  name = "Network"
  parent = "Topics"
  pageRef = "tags/network"
  weight = 24

[[main]]
  name = "About"
  pageRef = "about"
  weight = 30

[[footer]]
  name = "Tags"
  pageRef = "tags"
  weight = 10
